### ISSUE TITLE
Test for lab3 launches a GUI

### ISSUE THREAD

**Issue by kcpeppe** [henri-tremblay/DeadlockLabJavaOne2012#1]
Test for lab3 launches a GUI that requires the user to exit it in order for the build to continue. Do we really need unit tests for the labs? Can mvn control the GUI so a human doesn't have to

**Comment by kabutz** [comment]
Hi Henri,
do you know how we could launch a single class (for example Java2Demo)
using Maven?  We don't need the test case for labs 3 and 4.Regards

## Heinz

Dr Heinz M. Kabutz (PhD CompSci)
Author of "The Java(tm) Specialists' Newsletter"
Sun Java Champion
IEEE Certified Software Development Professional
http://www.javaspecialists.eu
Tel: +30 69 75 595 262
Skype: kabutz 

On 8/21/12 5:07 PM, Kirk Pepperdine wrote:

  Test for lab3 launches a GUI that requires the user to exit it in
order for the build to continue. Do we really need unit tests for the
labs? Can mvn control the GUI so a human doesn't have to
   —
Reply to this email directly or view
it on GitHub.

**Comment by henri-tremblay** [comment]
Yep. I'll check it in.

**Comment by henri-tremblay** [comment]
I just pushed a way to do it. On lab3 and lab4.

You can do there commands (both are doing the same thing)
mvn -Prun
mvn exec:java

Both will first compile and then launch the application. Maven will blocked
until the application is stopped (Ctrl+C will work).

**Comment by kcpeppe** [comment]
Agreed with Heinz.. sorry I don't know much about Maven or I'd remove the tests myself...

**Comment by henri-tremblay** [comment]
No problem. I'll remove them.

Are we talking only about lab 3 and 4?

**Comment by kcpeppe** [comment]
It's the only two that are annoying ;-)

**Comment by henri-tremblay** [comment]
Removed. In fact there was not much to do. Just to delete the two classes
(unless that wasn't what you want. Do you only want to disactivate them?)

**Comment by kabutz** [comment]
Yes, I think so.  Labs 1 & 2 are normal unit tests that simply fail
when things go wrong, without hanging up the whole maven build.Regards

## Heinz

Dr Heinz M. Kabutz (PhD CompSci)
Author of "The Java(tm) Specialists' Newsletter"
Sun Java Champion
IEEE Certified Software Development Professional
http://www.javaspecialists.eu
Tel: +30 69 75 595 262
Skype: kabutz 

On 8/21/12 7:55 PM, henri-tremblay wrote:
No problem. I'll remove them.

Are we talking only about lab 3 and 4?

**Comment by kabutz** [comment]
Perfect.  We don't want to have those two classes.Regards

## Heinz

Dr Heinz M. Kabutz (PhD CompSci)
Author of "The Java(tm) Specialists' Newsletter"
Sun Java Champion
IEEE Certified Software Development Professional
http://www.javaspecialists.eu
Tel: +30 69 75 595 262
Skype: kabutz 

On 8/21/12 7:59 PM, henri-tremblay wrote:
Removed. In fact there was not much to do. Just to delete
the two classes

(unless that wasn't what you want. Do you only want to disactivate
them?)

**Comment by henri-tremblay** [comment]
Since lab1 and 2 are using unit tests, there's no need to add the exec
plugin.

However, it means that when ran with Maven, Maven will freeze until the
deadlock is detected.

Won't that be difficult for our attendees? They won't be able to get the
stack trace.  Maybe a main class would be easier?

Also, right now, Maven isn't running any test because the test class should
be named "BlaBlaBla_Test_". So at least, I need to rename them.

**Comment by kcpeppe** [comment]
I agree, I'd prefer to run this from an exec:java. I think a main class is in order.

**Comment by henri-tremblay** [comment]
I'll do that then.

However I think the test should stay just to show how to detect a deadlock
in a unit test.

**Comment by kcpeppe** [comment]
while I agree that it's an interesting use case I think that it might be confusing and given our short time budgets... Anyways, I'll defer to Heinz's judgement as it's his lab.

**Comment by kabutz** [comment]
Sorry, you mean the semaphores running out in lab 3?
I think that it should be fairly easy to find if we prepare them
adequately for it.
Once they've got the hang of collecting stack traces, the rest should
be easy.Regards

## Heinz

Dr Heinz M. Kabutz (PhD CompSci)
Author of "The Java(tm) Specialists' Newsletter"
Sun Java Champion
IEEE Certified Software Development Professional
http://www.javaspecialists.eu
Tel: +30 69 75 595 262
Skype: kabutz 

On 8/21/12 8:38 PM, Kirk Pepperdine wrote:
while I agree that it's an interesting use case I think
that it might be confusing and given our short time budgets... Anyways,
I'll defer to Heinz's judgement as it's his lab.

**Comment by henri-tremblay** [comment]
On my side, I was talking about the unit tests for lab 1 and 2.

I'll go out now. I'll add the main for lab1 right now and the exec for both
labs when I'll be back.

**Comment by kabutz** [comment]
I'm off for tonight as well.  Early start tomorrow to fly to Athens to
fetch my mother.
I agree that all the labs should have a consistent way of running
them.  "mnv exec:java lab1" or something like that would be good for
each one.  We should probably also add batch files for the people to
use if they want to call the labs from the command line.  But that
would mean we have to also set up Maven and Java from the command
line.  Regards

## Heinz

Dr Heinz M. Kabutz (PhD CompSci)
Author of "The Java(tm) Specialists' Newsletter"
Sun Java Champion
IEEE Certified Software Development Professional
http://www.javaspecialists.eu
Tel: +30 69 75 595 262
Skype: kabutz 

On 8/21/12 9:02 PM, henri-tremblay wrote:
On my side, I was talking about the unit tests for lab 1
and 2.

I'll go out now. I'll add the main for lab1 right now and the exec for
both

labs when I'll be back.

**Comment by henri-tremblay** [comment]
Yep. But don't worry. That's my part... if we get the VirtualBox image at
some point...

**Comment by henri-tremblay** [comment]
Ok. Everything is now launched with mvn -Prun.

I however noticed that on my computer, lab1 isn't deadlocking all the time.
It does in less than 3 launch though.

**Comment by kabutz** [comment]
Hi Henri,
sorry, I'm slightly obtuse when it comes to Maven.  What commands must
I run from the main project directory to launch the various labs?
And what would I call from inside the labs?Regards

## Heinz

Dr Heinz M. Kabutz (PhD CompSci)
Author of "The Java(tm) Specialists' Newsletter"
Sun Java Champion
IEEE Certified Software Development Professional
http://www.javaspecialists.eu
Tel: +30 69 75 595 262
Skype: kabutz 

On 8/22/12 1:29 AM, henri-tremblay wrote:
Ok. Everything is now launched with mvn -Prun.

I however noticed that on my computer, lab1 isn't deadlocking all the
time.

It does in less than 3 launch though.

**Comment by henri-tremblay** [comment]
"mvn install" will compile all the labs from the root.

"mvn -Prun" will launch each lab in each lab directory

run.bat also.

**Comment by kabutz** [comment]
Did you push your latest changes?  mvn -Prun does not work for me. 
"mvn install" did work though.
I'm busy putting comments into the source files and will upload them
shortly.Regards

## Heinz

Dr Heinz M. Kabutz (PhD CompSci)
Author of "The Java(tm) Specialists' Newsletter"
Sun Java Champion
IEEE Certified Software Development Professional
http://www.javaspecialists.eu
Tel: +30 69 75 595 262
Skype: kabutz 

On 8/23/12 5:22 PM, henri-tremblay wrote:
"mvn install" will compile all the labs from the root.

"mvn -Prun" will launch each lab in each lab directory

run.bat also.

**Comment by henri-tremblay** [comment]
oh dear... no... Sorry about that. I missed a push.

I'm not on the same computer. I'll be able to do it in two or three hours.
