### ISSUE TITLE
mvn pom for lab 1

### ISSUE THREAD

**Issue by kcpeppe** [henri-tremblay/DeadlockLabJavaOne2012#2]
the Maven POM for lab1 will not run on it's own. IMO each lab should be able to run separately from each other.

**Comment by henri-tremblay** [comment]
I was planning to pre-compile the parent pom.

But I can modify it to have them all run independently.

**Comment by kcpeppe** [comment]
On 2012-08-21, at 4:12 PM, henri-tremblay notifications@github.com wrote:

> I was planning to pre-compile the parent pom. 

good idea but as each student works on a lab they should be able to work there independently of the other labs.

-- kirk

> But I can modify it to have them all run independently. 
>

**Comment by henri-tremblay** [comment]
They will. They will all have the parent pom pre-installed in their local
repository.

But, still, I'll modify that to remove some entropy.

**Comment by henri-tremblay** [comment]
Done. However, the dependency to util stays. So the util project will have
to be installed locally for the other projects to compile independently.
But that's not a problem.
