### ISSUE TITLE
mvn dependency download

### ISSUE THREAD

**Issue by kcpeppe** [henri-tremblay/DeadlockLabJavaOne2012#3]
We want to make sure that we've resolved all of the mvn dependencies so that during the lab mvn doesn't go off and download a whole pile a stuff for every machine.. that would be a network nightmare

**Comment by henri-tremblay** [comment]
Yes. Absolutely. The VM should have a filled local repository. I will
launch all the commands to make sure it is. And set the settings.xml to
offline.

**Comment by henri-tremblay** [comment]
Local repository prefilled
